BootStrap: debootstrap
OSVersion: bionic
MirrorURL: http://archive.ubuntu.com/ubuntu/


%runscript
    echo "This is what happens when you run the container..."


%post
    echo "Hello from inside the container"
    
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get -y update
    apt-get -y upgrade
    apt-get -y dist-upgrade

    apt-get install -y autoconf
    apt-get install -y cmake
    apt-get install -y curl
    apt-get install -y gdb
    apt-get install -y git
    apt-get install -y libboost-all-dev
    apt-get install -y libtool-bin
    apt-get install -y net-tools
    apt-get install -y vim

    apt-get install -y libssl-dev
    apt-get install -y zlib1g-dev

    apt-get clean

%environment
    export PATH=$PATH:/usr/local/bin
    export GCC_VERSION='5.5.0'
    export CPATH='/usr/local/include:/usr/lib'
    export PKG_CONFIG_PATH='/usr/local/lib/pkgconfig'
    export LD_LIBRARY_PATH='/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib'
