BootStrap: debootstrap
OSVersion: bionic
MirrorURL: http://archive.ubuntu.com/ubuntu/


%runscript
    echo "This is what happens when you run the container..."

%post
    echo "Hello from inside the container"

    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt-get update
    apt-get install -y wget
    apt-get install -y bzip2
    apt-get install -y gzip
    apt-get install -y autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev

    apt-get clean

    apt-get install -y bwa

    wget https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2
    tar -vxjf samtools-1.10.tar.bz2
    cd samtools-1.10
    ./configure && make && make install

%environment
    export PATH=$PATH:/usr/local/bin
    export GCC_VERSION='5.5.0'
    export CPATH='/usr/local/include:/usr/lib'
    export PKG_CONFIG_PATH='/usr/local/lib/pkgconfig'
    export LD_LIBRARY_PATH='/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib'
